server:
  port: 7003
  error:
    include-message: always

# Strongly recommend to set this property to "none" in a production environment!
spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost/review-db
    username: user
    password: pwd
    hikari:
      initializationFailTimeout: 60000
  cloud:
    stream:
      kafka:
        binder:
          brokers: 127.0.0.1:9092
          auto-create-topics: true
          configuration:
            auto.offset.reset: latest
      bindings:
        input:
          destination: reviews
          group: reviewsGroup
          consumer:
            maxAttempts: 3
            backOffInitialInterval: 500
            backOffMaxInterval: 1000
            backOffMultiplier: 2.0
            autoBindDlq: true
            republishToDlq: true
            enableDlq: true

logging:
  level:
    root: INFO
    se.magnus: DEBUG

management:
  endpoint:
    health:
      show-details: "ALWAYS"
  web:
    exposure:
      include: "*"
---
spring.profiles: docker

server.port: 8080

spring.datasource.url: jdbc:mysql://mysql/review-db

spring.rabbitmq.host: rabbitmq

spring.cloud.stream.kafka.binder.brokers: kafka