server:
  port: 7002
  error:
    include-message: always

app:
  eureka-username: u
  eureka-password: p
  eureka-server: localhost

eureka:
  client:
    serviceUrl:
      defaultZone: "http://${app.eureka-username}:${app.eureka-password}@${app.eureka-server}:8761/eureka/"
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

spring:
  application:
    name: recommendation
  data:
    mongodb:
      host: localhost
      port: 27017
      database: recommendation-db

  cloud:
    stream:
      kafka:
        binder:
          brokers: 127.0.0.1:9092
          auto-create-topics: true
          configuration:
            auto.offset.reset: latest
      bindings:
        input:
          destination: recommendations
          group: recommendationsGroup
          consumer:
            maxAttempts: 3
            backOffInitialInterval: 500
            backOffMaxInterval: 1000
            backOffMultiplier: 2.0
            autoBindDlq: true
            republishToDlq: true
            enableDlq: true


logging:
  level:
    root: INFO
    se.magnus: DEBUG

management:
  endpoint:
    health:
      show-details: "ALWAYS"
  web:
    exposure:
      include: "*"
---
spring.profiles: docker

server.port: 8080

spring.data.mongodb.host: mongodb

spring.cloud.stream.kafka.binder.brokers: kafka

app.eureka-server: eureka