server.port: 7001
server.error.include-message: always

logging:
  level:
    root: INFO
    se.magnus: DEBUG

spring.data.mongodb:
  host: localhost
  port: 27017
  database: product-db

---
spring.profiles: docker
server.port: 8080
spring.data.mongodb.host: mongodb

